config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :items do
    resources :expenses, only: :edit
  end
  resources :item_users, only: [:create, :destroy]
  resources :expenses, only: [:create, :update, :destroy]
  resources :expense_users, only: [:create, :destroy]
  resources :payments, only: [:create, :update, :destroy]

  get(
    'calculators/calculate_amounts/:item_id' => 'calculators#calculate_amounts',
    as: 'calculate'
  )

  # authenticate :user, lambda { |u| u.admin? } do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api do
    get 'users/:id/available_users_item' => 'users#available_users_item'
  end

  root 'items#index'
end

app/models/item.rb
class Item < ApplicationRecord
  has_many :item_users, dependent: :destroy
  has_many :expenses, dependent: :destroy
  has_many :payments, dependent: :destroy
  belongs_to :user

  validates :name, presence: true

  scope :my_items, ->(user_id) { where(user_id: user_id) }

  scope :items_which_i_participate, (lambda do |user_id|
    joins(:item_users).where('items.user_id <> ? AND item_users.user_id = ?', user_id, user_id)
  end)

  scope :allow_show, (lambda do |user_id|
    joins(:item_users).where('item_users.user_id = ?', user_id)
  end)
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource

  expose :my_items, -> { Item.my_items(current_user) }
  expose :items_which_i_participate, -> { Item.items_which_i_participate(current_user) }
  expose :item
  expose :item_user, -> { ItemUser.new }
  expose :item_users, -> { ItemUser.get_participants(params[:id]) }
  expose :expense
  expose :expenses, -> { Expense.where(item_id: params[:id]) }
  expose :payments, -> { Payment.includes(:user).where(item_id: params[:id]) }
  expose :expenses_not_paid, -> { Expense.not_paid(params[:id]) }

  def create
    if item.save
      redirect_to items_path
    else
      render :new
    end
  end

  def update
    if item.update(item_params)
      redirect_to item_path(item.id)
    else
      render :edit
    end
  end

  def destroy
    item.destroy
    redirect_to items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description).merge(user_id: current_user.id)
  end
end

app/views/items/_form.html.haml
%h1 Add new Item

= simple_form_for item do |f|
  = f.input :name
  = f.input :description, as: :text
  = f.button :submit

app/views/items/_list.html.haml
%h2= title
- items.each do |i|
  %p
    = i.name
    = link_to 'Show', item_path(i)
    - if can? :destroy, i
      = link_to 'Delete', item_path(i), method: :delete

app/views/items/edit.html.haml
= render 'form'

app/views/items/index.html.haml
%h1 Items

= link_to 'Add', new_item_path, class: 'btn btn-success'

= render 'list', title: 'My items',items: my_items
= render 'list', title: 'Items which I participate',items: items_which_i_participate

app/views/items/new.html.haml
= render 'form'

app/views/items/show.html.haml
%h1 Item
%p= item.name
%p= simple_format(item.description)

- if can? :edit, item
  %p= link_to 'Edit', edit_item_path(item), class: 'btn btn-success'

= render 'item_users/autocomplete_box', user_rec: item_user

%hr
= render 'partials/user_records', users_rec: item_users, user_controller: 'item_users', expense_id: ''

%hr
= render 'expenses/new'

%hr
%div{id: 'expenses'}
  - expenses.each do |e|
    = render 'expenses/record', e: e