config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  resources :items do
    resources :expenses, only: :edit
  end
  resources :item_users, only: [:create, :destroy]
  resources :expenses, only: [:create, :update, :destroy]
  resources :expense_users, only: [:create, :destroy]
  resources :payments, only: [:create, :update, :destroy]

  get(
    'calculators/calculate_amounts/:item_id' => 'calculators#calculate_amounts',
    as: 'calculate'
  )

  # authenticate :user, lambda { |u| u.admin? } do
  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  namespace :api do
    get 'users/:id/available_users_item' => 'users#available_users_item'
  end

  root 'items#index'
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  expose :expense
  expose :item_users, -> { ItemUser.get_participants(expense_params[:item_id]) }
  expose :item_id, -> { params[:item_id] }

  def create
    ActiveRecord::Base.transaction do
      users_ids = item_users.pluck(:user_id)

      expense.number_of_participants = users_ids.count
      expense.save

      insert_sql = ExpenseUser.inserts(users_ids, expense)

      sql = "INSERT INTO expense_users (\"expense_id\", \"user_id\", \"created_at\", \"updated_at\")
       VALUES #{insert_sql.join(', ')}"

      ActiveRecord::Base.connection.execute sql
    end
  end

  def destroy
    expense.destroy
  end

  def update
    expense.update(expense_params)
  end

  private

  def expense_params
    params.require(:expense).permit(:name, :amount, :item_id)
  end
end

app/views/expenses/_form.html.haml
= simple_form_for record, remote: true do |f| 
  = f.input :item_id, as: :hidden, input_html: { value: item_id }
  = f.input :name
  = f.input :amount
  = f.button :submit

app/views/expenses/_new.html.haml
= render 'expenses/form', record: Expense.new, item_id: item.id

app/views/expenses/_record.html.haml
.box.box-default{id: "expense_#{e.id}"}
  .box-header.with-border
    %h3.box-title #{e.name} - #{e.amount}
    = link_to '(edit)', edit_item_expense_path(e.item_id, e.id), remote: true
    = link_to '(remove)', expense_path(e.id), method: :delete, remote: true

    .box-tools.pull-right
      %button.btn.btn-box-tool{"data-toggle" => "tooltip", "data-widget" => "collapse", :title => "Collapse"}
        %i.fa.fa-minus

  .box-body
    .row
      .col-md-6
        %div{id: "expense_edit_#{e.id}"}

      .col-md-3
        = render 'expense_users/select_box', expense_id: e.id
        = render 'partials/user_records', users_rec: ExpenseUser.get_participants(e.id), user_controller: 'expense_users', expense_id: e.id
      .col-md-3{id: "payment_#{e.id}"}
        = render 'payments/form', e: e, payment_obj: Payment.find_by(expense_id: e.id) || Payment.new

app/views/expenses/create.js.haml
$("#expenses").append("#{j render('/expenses/record', e: expense)}")
$("#new_expense")[0].reset()

app/views/expenses/destroy.js.haml
$("#expense_#{expense.id}").remove()

app/views/expenses/edit.js.haml
$("#expense_edit_#{expense.id}").append("#{j render('expenses/form', record: expense, item_id: item_id)}")

app/views/expenses/update.js.haml
$("#expense_#{expense.id} h3").text("#{expense.name} - #{expense.amount}")
$("#expense_edit_#{expense.id}").empty()